languageCode = "en-us"
baseurl = "https://johntduong.github.io/portfolio/"
title = "John Duong"
publishDir = "docs"
themesDir = "themes"
theme = "prologue"

[params]
  name = "John Duong"
  description = "Software Engineer"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/johntduong"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/johntduong/"

[[params.social]]
  medium = "angellist"
  icon = "angellist"
  link = "https://angel.co/john-duong-3"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:duong.johnpaul@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Quotely"
  alt = ""
  source = "img/quotely.png"
  url = "https://github.com/johntduong/Quoted"
  description = "Quotely is a group SMS management platform for sending and receiving text or voice messages to nearby businesses or contacts. Built with React and MongoDB."

[[params.portfolio1]]
  title = "EventScore"
  alt = ""
  source = "img/eventscore.png"
  url = "https://github.com/johntduong/Eventscore"
  description = "EventScore is a mobile app that recommends concerts based on scores calculated using numer of followers, ticket demand, and social perception. Built with React Native, Redux, Node.js, and MongdoDB."

# Portfolio column two

[[params.portfolio2]]
  title = "Forkly"
  alt = ""
  source = "img/forkly.png"
  url = "https://forkly-shielded-oasis-16105.herokuapp.com/"
  description = "Forkly is a recipe app with version control that lets users fork and improve on shared cooking recipes. Built with React, Node.js, and MongoDB."

# Portfolio column 3
