languageCode = "en-us"
baseurl = "https://johntduong.github.io/portfolio/"
title = "John Duong"
publishDir = "docs"
themesDir = "themes"
theme = "prologue"

[params]
  name = "John Duong"
  description = "Software Developer"
  copyright = "Untitled."

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/john.duong.714"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/johntduong"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/johntduong/"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:duong.johnpaul@gmail.com"

# Portfolio column one

# Portfolio column two

[[params.portfolio2]]
  title = "EventScore"
  alt = ""
  source = "img/eventscore.png"
  url = "#"

[[params.portfolio2]]
  title = "Forkly"
  alt = ""
  source = "img/forkly.png"
  url = "https://forkly-shielded-oasis-16105.herokuapp.com/"

[[params.portfolio2]]
  title = "Quotely"
  alt = ""
  source = "img/quotely.png"
  url = "#"

# Portfolio column 3
